import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import peopleJson from '../libs/people-data';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import Header from './components/header';

export default function Home() {
	const router = useRouter();
	const [characters, setCharacters] = useState([]);
	const handleOnChange = (guid) => {
		router.push(`/details/${guid}`);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<main className={styles.main}>
				<div>
					{peopleJson.map(({ name, guid }) => {
						return (
							<div key={guid}>
								<h1
									onClick={() => handleOnChange(guid)}
									style={{ cursor: 'pointer' }}>
									{name}
								</h1>
							</div>
						);
					})}
				</div>
			</main>
		</div>
	);
}
